---

- name: install rust by script
  vars:
    installer: /tmp/rust-installer.sh
  block:
  - name: download installer
    get_url:
      url: https://sh.rustup.rs/
      dest: "{{ installer }}"

  - name: install rust
    script: "{{ installer }} -y"
    register: install
    changed_when: "'existing' not in install.stderr"

- name: install rust
  become: yes
  package:
    name: "{{ item }}"
  loop:
    - rustc
    - cargo

- name: install rust tools
  import_tasks: tools.yml
