---
- name: install depedency of exa
  package:
    name: cmake
  become: yes

- name: "install tools by cargo"
  shell: "cargo install {{ item.crate | default(item.name) }}"
  register: cargo_install
  failed_when: cargo_install.rc != 0
  changed_when: |
    'Ignored' not in cargo_install.stderr
  loop:
    - name: exa # TODO: install binary
    - name: fd
      crate: fd-find
    - name: ripgrep
    - name: tac
